name: reze_melhor
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  #Packages
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17 
  intl: ^0.19.0
  table_calendar: 3.1.3
  lucid_validation: ^1.2.5
  image_picker: ^1.1.2
  introduction_screen: ^3.1.17
  dots_indicator: ^4.0.1
  flutter_local_notifications: ^18.0.1
  logger: ^2.0.2
  flutter_timezone: ^4.1.0
  permission_handler: ^11.4.0
  #Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  firebase_app_check: ^0.3.2+4
  firebase_messaging: ^15.2.4
  firebase_crashlytics: ^4.3.4
  #Database
  objectbox: ^4.1.0
  ulid: ^2.0.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  firebase_analytics: ^11.4.4
  objectbox_flutter_libs: ^4.1.0
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/animations/
    - assets/json/

