// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwYuqW6eQVUgBo6NWbjSgeIlrtksbIMTE',
    appId: '1:612236078847:android:e90a4dc9fb6bca8803a6ca',
    messagingSenderId: '612236078847',
    projectId: 'rezemelhor',
    storageBucket: 'rezemelhor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC1zYkRMHzaEupzqtpwvu9t_G7SBMSoCc',
    appId: '1:612236078847:ios:cf230bbee208ae7b03a6ca',
    messagingSenderId: '612236078847',
    projectId: 'rezemelhor',
    storageBucket: 'rezemelhor.appspot.com',
    androidClientId: '612236078847-cgnemo6kd7r9c3c6925ludasnjpko5qk.apps.googleusercontent.com',
    iosClientId: '612236078847-69oaapusrmj11265v6m0p5t1d8v3vmmc.apps.googleusercontent.com',
    iosBundleId: 'com.rezeMelhor',
  );

}