// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'domain/entities/biblia.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 978354530695307512),
      name: 'Biblia',
      lastPropertyId: const obx_int.IdUid(3, 3609933219412969673),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 35229122984407765),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7696647299759706750),
            name: 'velhoTestamentoId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 5837581138182094753),
            relationTarget: 'Testamento'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3609933219412969673),
            name: 'novoTestamentoId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 4436225505688040395),
            relationTarget: 'Testamento')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 2776166888091952450),
      name: 'Capitulo',
      lastPropertyId: const obx_int.IdUid(3, 3250736292200470131),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5218771542444322021),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3250736292200470131),
            name: 'numero',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 8296689231686661436),
            name: 'versiculos',
            targetId: const obx_int.IdUid(5, 8396685455678618413))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 5353356144790035989),
      name: 'Testamento',
      lastPropertyId: const obx_int.IdUid(2, 427727005206992345),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2387665716135683757),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 427727005206992345),
            name: 'nome',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(4, 4371736052324638455),
            name: 'livros',
            targetId: const obx_int.IdUid(6, 6339586086367043129))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 8396685455678618413),
      name: 'Versiculo',
      lastPropertyId: const obx_int.IdUid(3, 8583305453968248019),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7806245502070636438),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5590735662660648335),
            name: 'numero',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8583305453968248019),
            name: 'conteudo',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 6339586086367043129),
      name: 'Livro',
      lastPropertyId: const obx_int.IdUid(2, 5508764048416290882),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4397438891995134128),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5508764048416290882),
            name: 'nome',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 6494389622508671702),
            name: 'capitulos',
            targetId: const obx_int.IdUid(3, 2776166888091952450))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(6, 6339586086367043129),
      lastIndexId: const obx_int.IdUid(3, 4436225505688040395),
      lastRelationId: const obx_int.IdUid(4, 4371736052324638455),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [8161291061944171036],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        1515708134120394993,
        6261833103580489849,
        1658293469330019822,
        3236633171394263372,
        3725834056642003008,
        4394997633896901442,
        5897502857700167867
      ],
      retiredRelationUids: const [6253594921626277455],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Biblia: obx_int.EntityDefinition<Biblia>(
        model: _entities[0],
        toOneRelations: (Biblia object) =>
            [object.velhoTestamento, object.novoTestamento],
        toManyRelations: (Biblia object) => {},
        getId: (Biblia object) => object.id,
        setId: (Biblia object, int id) {
          object.id = id;
        },
        objectToFB: (Biblia object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.velhoTestamento.targetId);
          fbb.addInt64(2, object.novoTestamento.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Biblia()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.velhoTestamento.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.velhoTestamento.attach(store);
          object.novoTestamento.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.novoTestamento.attach(store);
          return object;
        }),
    Capitulo: obx_int.EntityDefinition<Capitulo>(
        model: _entities[1],
        toOneRelations: (Capitulo object) => [],
        toManyRelations: (Capitulo object) =>
            {obx_int.RelInfo<Capitulo>.toMany(1, object.id): object.versiculos},
        getId: (Capitulo object) => object.id,
        setId: (Capitulo object, int id) {
          object.id = id;
        },
        objectToFB: (Capitulo object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.numero);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final numeroParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = Capitulo(numero: numeroParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<Capitulo>(object.versiculos,
              store, obx_int.RelInfo<Capitulo>.toMany(1, object.id));
          return object;
        }),
    Testamento: obx_int.EntityDefinition<Testamento>(
        model: _entities[2],
        toOneRelations: (Testamento object) => [],
        toManyRelations: (Testamento object) =>
            {obx_int.RelInfo<Testamento>.toMany(4, object.id): object.livros},
        getId: (Testamento object) => object.id,
        setId: (Testamento object, int id) {
          object.id = id;
        },
        objectToFB: (Testamento object, fb.Builder fbb) {
          final nomeOffset = fbb.writeString(object.nome);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Testamento(nome: nomeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<Testamento>(object.livros,
              store, obx_int.RelInfo<Testamento>.toMany(4, object.id));
          return object;
        }),
    Versiculo: obx_int.EntityDefinition<Versiculo>(
        model: _entities[3],
        toOneRelations: (Versiculo object) => [],
        toManyRelations: (Versiculo object) => {},
        getId: (Versiculo object) => object.id,
        setId: (Versiculo object, int id) {
          object.id = id;
        },
        objectToFB: (Versiculo object, fb.Builder fbb) {
          final conteudoOffset = fbb.writeString(object.conteudo);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.numero);
          fbb.addOffset(2, conteudoOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final numeroParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final conteudoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = Versiculo(numero: numeroParam, conteudo: conteudoParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Livro: obx_int.EntityDefinition<Livro>(
        model: _entities[4],
        toOneRelations: (Livro object) => [],
        toManyRelations: (Livro object) =>
            {obx_int.RelInfo<Livro>.toMany(3, object.id): object.capitulos},
        getId: (Livro object) => object.id,
        setId: (Livro object, int id) {
          object.id = id;
        },
        objectToFB: (Livro object, fb.Builder fbb) {
          final nomeOffset = fbb.writeString(object.nome);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Livro(nome: nomeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<Livro>(object.capitulos,
              store, obx_int.RelInfo<Livro>.toMany(3, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Biblia] entity fields to define ObjectBox queries.
class Biblia_ {
  /// See [Biblia.id].
  static final id =
      obx.QueryIntegerProperty<Biblia>(_entities[0].properties[0]);

  /// See [Biblia.velhoTestamento].
  static final velhoTestamento =
      obx.QueryRelationToOne<Biblia, Testamento>(_entities[0].properties[1]);

  /// See [Biblia.novoTestamento].
  static final novoTestamento =
      obx.QueryRelationToOne<Biblia, Testamento>(_entities[0].properties[2]);
}

/// [Capitulo] entity fields to define ObjectBox queries.
class Capitulo_ {
  /// See [Capitulo.id].
  static final id =
      obx.QueryIntegerProperty<Capitulo>(_entities[1].properties[0]);

  /// See [Capitulo.numero].
  static final numero =
      obx.QueryIntegerProperty<Capitulo>(_entities[1].properties[1]);

  /// see [Capitulo.versiculos]
  static final versiculos =
      obx.QueryRelationToMany<Capitulo, Versiculo>(_entities[1].relations[0]);
}

/// [Testamento] entity fields to define ObjectBox queries.
class Testamento_ {
  /// See [Testamento.id].
  static final id =
      obx.QueryIntegerProperty<Testamento>(_entities[2].properties[0]);

  /// See [Testamento.nome].
  static final nome =
      obx.QueryStringProperty<Testamento>(_entities[2].properties[1]);

  /// see [Testamento.livros]
  static final livros =
      obx.QueryRelationToMany<Testamento, Livro>(_entities[2].relations[0]);
}

/// [Versiculo] entity fields to define ObjectBox queries.
class Versiculo_ {
  /// See [Versiculo.id].
  static final id =
      obx.QueryIntegerProperty<Versiculo>(_entities[3].properties[0]);

  /// See [Versiculo.numero].
  static final numero =
      obx.QueryIntegerProperty<Versiculo>(_entities[3].properties[1]);

  /// See [Versiculo.conteudo].
  static final conteudo =
      obx.QueryStringProperty<Versiculo>(_entities[3].properties[2]);
}

/// [Livro] entity fields to define ObjectBox queries.
class Livro_ {
  /// See [Livro.id].
  static final id = obx.QueryIntegerProperty<Livro>(_entities[4].properties[0]);

  /// See [Livro.nome].
  static final nome =
      obx.QueryStringProperty<Livro>(_entities[4].properties[1]);

  /// see [Livro.capitulos]
  static final capitulos =
      obx.QueryRelationToMany<Livro, Capitulo>(_entities[4].relations[0]);
}
